#!/usr/bin/env bash
# Configures ngnix server to have a custom 404 page containing the string
# Ceci n'est pas une page.
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
notfound="error_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "s|\#error_page 404 /404.html;|$notfound|" /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo service nginx reload
