#!/usr/bin/env bash
# Configures ngnix server to have a custom 404 page containing the string
# Ceci n'est pas une page.
sudo echo "Ceci n'est pas une page." | sudo tee /usr/share/nginx/html/404.html
notfound="error_page 404 /404.html;"
sudo sed -i "s|\#error_page 404 /404.html;|$notfound|" /etc/nginx/sites-enabled/default
sudo service nginx restart
