#!/usr/bin/env bash
# Configures server to make sure Nginx is running and listening on port 80
# of all the server's active IPv4 IPs
apt-get update
apt-get install nginx
sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
service nginx start
service nginx stop
