#!/usr/bin/env bash
# Creates the file /var/run/holbertonscript.pid, displays "To infinity and
# beyond" infinitely, displays "I hate the kill command" when receiving a
# SIGTERM signal, "Y U no love me?!" when receiving a SIGINT signal, and
# deletes the file and terminates when receiving a SIGQUIT or SIGTERM signal
echo "$$" > /var/run/holbertonscript.pid

function clean_up {
    sudo rm /var/run/holbertonscript.pid
}

trap 'echo \"I hate the kill command\";
clean_up; kill -9 \"$(</var/run/holbertonscript.pid)\"' SIGTERM
trap "echo \"Y U no love me?!\"" SIGINT
trap 'clean_up; kill -9 \"$(</var/run/holbertonscript.pid)\"' SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done

clean_up
