#!/usr/bin/env bash
# Loops from 1 to 10 and displays "bad luck" for 4th loop, "good luck" for
# 8th loop, and "Holberton School" for other iterations
i="1"
while [ $i -lt 11 ]
do
    if [ $i == 4 ]
	then echo "bad luck"
    elif [ $i == 8 ]
	then echo "good luck"
    else
	echo "Holberton School"
    fi
    i=$((i+1))
done
