#!/usr/bin/env bash
# Displays numbers 1 to 20 and displays "bad luck from China" for the 4th
# iteration, "bad luck from Japan" for the 9th iteration, and "bad luck
# from Italy" for the 17th iteration
i="1"
while [ $i -lt 21 ]
do
    case $i in
	4) echo $i
	    echo "bad luck from China";;
	9) echo $i
	    echo "bad luck from Japan";;
	17) echo $i
	    echo "bad luck from Italy";;
	*) echo $i
    esac
    i=$((i+1))
done
