#!/usr/bin/env bash
# Installs HAProxy and configures to send traffic to web-01 and web-02
# with roundrobin algorithm
sudo apt-get update
sudo apt-get -y install haproxy
sudo sed -i -e "\$aENABLED=1" /etc/default/haproxy
sudo service haproxy start
