#!/usr/bin/env bash
# Change nginx owner to nginx instead of root
sudo pkill -f apache2
sudo service nginx stop
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo service nginx start
